source "https://rubygems.org"

# Use GitHub Pages plugin for Jekyll
gem "github-pages", group: :jekyll_plugins

# Plugins for additional features
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby-specific dependencies
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` for JRuby builds
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
